# config actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all actuator endpoints over HTTP
  endpoint:
    shutdown:
      access: unrestricted  # Allow unrestricted access to the shutdown endpoint
      # NOTE: only use this shutdown endpoint config in dev env
  info:
    env:
      enabled: true         # show info env in /actuator/info

# swagger-ui
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

webhook:
  base-uri: ${WEBHOOK_BASE_URI:https://0fb1d3e2bc11.ngrok-free.app}